### ISSUE TITLE
Project visibility

### ISSUE THREAD

**Issue by Solido** [jolleekin/modern_charts#11]
You should add some screenshots on Readme to help adoption of the lib

**Comment by jolleekin** [comment]
Thanks for your feedback. I wanted to create an interactive demo page on github.io but haven't got time for that. While waiting for that to come, you can look at the [docs](https://github.com/jolleekin/modern_charts/wiki/Docs) instead.

**Comment by jolleekin** [comment]
I updated README to include some screenshots.
