### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by Solido** [jolleekin/modern_charts#12]
How difficult would it be to adapt the canvas code to Flutter.io ?

**Comment by jolleekin** [comment]
I don't use Flutter, so the short answer is I don't know. If you're interested in porting this package to Flutter, feel free to do it.

**Comment by angel1st** [comment]
@Solido - did you find a way to port this to Flutter? If not, did you find a descent substitute for this package already implemented in Dart / Flutter?

**Comment by Solido** [comment]
@angel1st https://github.com/Solido/awesome-flutter#charts

**Comment by jolleekin** [comment]
@angel1st 
https://pub.dartlang.org/packages/charts_flutter
https://pub.dartlang.org/packages/flutter_charts

**Comment by angel1st** [comment]
Thanks, @Solido , @jolleekin for your feedback. 
I am aware about the above mentioned packages, however, I have a specific requirement - I need a gauge chart with the value placed in the center. Something I can see in this package out of the box. Anyway - I managed it on my own.
